Repository klxiaoniu/QQVersionList, pull requests merged in 2024-05, with the labels that each got.

#40 临时方案修复浮动按钮跳动问题、新增可设置测试版猜版默认后缀
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_setting.xml
  app/src/main/res/layout/dialog_suffix_define.xml
  build.gradle.kts
Labels: Bug 修复, 新特性, 未经充分测试

#43 上游更新、异步读取猜版后缀字符串、新增“已安装”标识
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/VersionAdapter.kt
  app/src/main/res/layout/dialog_setting.xml
  app/src/main/res/layout/item_version.xml
  app/src/main/res/layout/item_version_detail.xml
  build.gradle.kts
Labels: 新特性, 优化与增强, 未经充分测试

#49 修复猜版"测试版"、"空格版"小版本号为空时的NPE问题
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
Labels: Bug 修复

#48 更换GsonBuild被废弃语句、重写“已安装”标识逻辑
  .idea/kotlinc.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/xiaoniu/qqversionlist/data/QQVersionBean.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/VersionAdapter.kt
  app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
  app/src/main/java/com/xiaoniu/qqversionlist/util/StringUtil.kt
  build.gradle.kts
  gradle.properties
Labels: Bug 修复, 优化与增强, 未经充分测试
