Repository klxiaoniu/QQVersionList, pull requests merged in 2024-04, with the labels that each got.

#29 去除可能存在的系统栏遮罩、去除点击猜版Spinner就隐藏软键盘的逻辑、关于页作者添加“其他贡献者”、修复版本列表部分文字无法触发长按动作的问题、优化猜版对话框点击开始后关闭软键盘
  README.md
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/VersionAdapter.kt
  app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
  app/src/main/res/layout/item_version.xml
  app/src/main/res/layout/item_version_detail.xml
Labels: bug

#32 适配 Splash Screen 启动画面
  app/build.gradle.kts
  app/src/main/java/com/xiaoniu/qqversionlist/TipTimeApplication.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground_dark.xml
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 新特性

#34 扩展猜版正式版和测试版直链格式
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/res/layout/dialog_setting.xml
Labels: 优化与增强, 未经充分测试

#35 分享字符串添加风险提示，上游更新：Gradle、Kotlin和Splash Screen，新增DataStore
  .idea/kotlinc.xml
  app/build.gradle.kts
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: 优化与增强

#37 更改版本列表界面、修复RTL语言下布局问题、DataStore封装改为内部协程、用列表切换逻辑替换猜版矢代码
  app/build.gradle.kts
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/VersionAdapter.kt
  app/src/main/java/com/xiaoniu/qqversionlist/util/SpUtil.kt
  app/src/main/res/layout/item_version.xml
  app/src/main/res/layout/item_version_detail.xml
Labels: Bug 修复, 优化与增强, 未经充分测试

#38 perf: getData after UA is agreed
  app/build.gradle.kts
  app/src/main/java/com/xiaoniu/qqversionlist/data/QQVersionBean.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/VersionAdapter.kt
  app/src/main/java/com/xiaoniu/qqversionlist/util/Extensions.kt
Labels: 优化与增强

#39 新增自定义猜版后缀，修复扩展测试版猜版时无法猜测 _64 后缀的问题
  README.md
  app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
  app/src/main/java/com/xiaoniu/qqversionlist/ui/VersionAdapter.kt
  app/src/main/res/drawable/arrow_right_s_line.xml
  app/src/main/res/drawable/save_line.xml
  app/src/main/res/layout/dialog_setting.xml
  app/src/main/res/layout/dialog_suffix_define.xml
  app/src/main/res/layout/item_version.xml
  app/src/main/res/layout/item_version_detail.xml
Labels: Bug 修复, 新特性
